import { CANON_NAMES } from "../categories/canon";

export const BRAND_MAP: Record<string, string[]> = {
  // === spending buckets ===
  Amazon: ["amazon", "amzn"],
  Starbucks: ["starbucks", "sbux", "sbx"],

  Shopping: [
    "target",
    "best buy",
    "home depot",
    "lowes",
    "ikea",
    "macys",
    "nordstrom",
    "kohls",
    "dillards",
    "wayfair",
    "etsy",
    "newegg",
    "micro center",
    "b&h",
  ],

  Groceries: [
    "wal mart",
    "wm superc",
    "wm super center",
    "wm supercenter",
    "neighborhood market",
    "kroger",
    "publix",
    "safeway",
    "vons",
    "meijer",
    "heb",
    "giant",
    "food lion",
    "wegmans",
    "aldi",
    "whole foods",
    "trader joes",
    "harris te",
    "harris teeter",
    "sprouts",
  ],

  Fuel: [
    "shell",
    "bp",
    "exxon",
    "chevron",
    "speedway",
    "sunoco",
    "wawa",
    "pilot",
    "7 eleven",
    "circle k",
  ],

  "Home/Utilities": [
    "dominion",
    "duke energy",
    "georgia power",
    "coned",
    "pg&e",
    "naturalgas",
    "xfinity",
    "comcast",
    "spectrum",
    "verizon",
    "at&t",
    "t mobile",
    "cox",
  ],

  Insurance: [
    "geico",
    "state farm",
    "allstate",
    "progressive",
    "usaa",
    "nationwide",
    "liberty mutual",
    "anthem",
    "cigna",
    "humana",
    "united healthcare",
    "insurance", // keep last—broad match
  ],

  Entertainment: [
    "amc",
    "regal",
    "fandango",
    "cinemark",
    "cinema cafe",
    "ticketmaster",
    "stubhub",
    "live nation",
  ],

  Subscriptions: [
    "netflix",
    "spotify",
    "hulu",
    "disney+",
    "paramount+",
    "discovery+",
    "apple tv",
    "apple music",
    "max",
    "youtube premium",
    "audible",
    "prime video",
  ],

  "Vehicle/City Related": [
    "parkmobile",
    "parkwhiz",
    "paybyphone",
    "passport parking",
    "ezpass",
    "e-zpass",
    "toll",
    "dmv",
    "meter fee",
    "parking",
  ],

  // === dining buckets ===
  "Fast Food": [
    "mcdonald",
    "burger king",
    "chick fil a",
    "wendy",
    "sonic",
    "taco bell",
    "kfc",
    "subway",
    "5guys",
    "five guys",
    "panda express",
    "arby",
    "chipotle",
    "panera",
    "bojangles",
    "little caesars",
    "pizza hut",
    "domino's",
    "papa john",
    "popeyes",
    "jimmy john",
    "jersey mike",
    "culver",
    "whataburger",
    "in n out",
    "shake shack",
    "dairy queen",
    "zaxby",
    "qdoba",
    "del taco",
    "el pollo loco",
    "wingstop",
    "raising cane",
    "churchs chicken",
    "freddys",
  ],

  Dining: [
    "restaurant",
    "bistro",
    "brasserie",
    "cantina",
    "taqueria",
    "tavern",
    "pub",
    "grill",
    "texas roadhouse",
    "steakhouse",
    "oyster bar",
    "cafe",
    "ristorante",
    "trattoria",
  ],

  // === life/admin buckets ===
  Doctors: [
    "urgent care",
    "clinic",
    "medical",
    "pediatrics",
    "dermatology",
    "radiology",
    "imaging",
    "orthopedic",
    "labcorp",
    "quest diagnostics",
    "dental",
    "dentist",
    "orthodontic",
    "optometry",
    "ophthalmology",
  ],

  Memberships: [
    "ymca",
    "planet fitness",
    "la fitness",
    "gold's gym",
    "anytime fitness",
    "aaa",
    "aarp",
    "costco",
    "sam's club",
    "bjs",
  ],

  Allowance: ["allowance", "greenlight", "gohenry", "famzoo"],

  "Income/Payroll": [
    "adp",
    "paychex",
    "gusto",
    "intuit payroll",
    "square payroll",
    "direct deposit",
    "payroll",
  ],

  "Transfer: Savings": [
    "online scheduled transfer",
    "auto transfer",
    "transfer to savings",
  ],

  "Transfer: Investing": [
    "vanguard",
    "fidelity",
    "schwab",
    "robinhood",
    "etrade",
    "betterment",
    "wealthfront",
  ],

  "Rent/Mortgage": [
    "newrez",
    "shellpoint",
    "shellpoin", // ✅ covers "Newrez-Shellpoin ACH Pmt"
    "rocket mortgage",
    "quicken loans",
    "mr. cooper",
    "loancare",
    "pennymac",
    "freedom mortgage",
    "guild mortgage",
    "fairway independent",
    "pnc mortgage",
    "truist mortgage",
    "us bank home mortgage",
    "caliber home loans",
    "navy federal mortgage",
    "zillow rent",
    "rentpayment",
    "appfolio",
    "yardi",
    "buildium",
    "avail",
  ],

  Debt: [
    "cardmember services",
    "navient",
    "nelnet",
    "aidvantage",
    "mohela",
    "great lakes",
    "sallie mae",
    "sofi",
    "lendingclub",
    "upstart",
    "marcus",
    "prosper",
    "best egg",
    "one main",
    // Bank + explicit finance/loan context
    "chase auto finance",
    "capital one auto finance",
    "truist loan",
    "truist auto",
    "loan payment",
    "installment loan",
    "personal loan",
    "student loan",
    "auto finance",
    "card payment",
  ],

  "Impulse/Misc": [
    // intentionally lightweight; avoid overreach
    "vending",
    "gift shop",
    "convenience store",
  ],

  // === new: travel ===
  Travel: [
    // air
    "delta",
    "american airlines",
    "united",
    "southwest",
    "jetblue",
    "spirit",
    "frontier",
    "alaska airlines",
    // lodging
    "marriott",
    "hilton",
    "hyatt",
    "ihg",
    "airbnb",
    "vrbo",
    "booking.com",
    "expedia",
    "hotels.com",
    // rail/bus
    "amtrak",
    "greyhound",
    "megabus",
    // car rental
    "enterprise",
    "hertz",
    "avis",
    "budget",
    "national",
    "alamo",
    "thrifty",
    "dollar",
    "turo",
    // rideshare / travel services
    "uber",
    "lyft",
    "tsaprecheck",
    "clear",
  ],
};

(() => {
  const bad = Object.keys(BRAND_MAP).filter((k) => !CANON_NAMES.has(k));
  if (bad.length) {
    console.warn("[BRAND_MAP] Non-canonical category keys:", bad);
  }
})();
