// lib/categories/defaults.ts
import type { Category } from "@/app/providers/CategoriesProvider";

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: crypto.randomUUID(),
    name: "Fast Food",
    icon: "🍟",
    color: "#ef4444",
    hint: "McDonald’s, Chick-fil-A",
    slug: "fast-food",
  },
  {
    id: crypto.randomUUID(),
    name: "Dining",
    icon: "🍽️",
    color: "#f59e0b",
    hint: "Date nights, high-end restaurants",
    slug: "dining",
  },
  {
    id: crypto.randomUUID(),
    name: "Groceries",
    icon: "🛒",
    color: "#22c55e",
    hint: "Harris Teeter, Kroger, Publix",
    slug: "groceries",
  },
  {
    id: crypto.randomUUID(),
    name: "Fuel",
    icon: "⛽",
    color: "#10b981",
    hint: "Shell, BP, Exxon",
    slug: "fuel",
  },
  {
    id: crypto.randomUUID(),
    name: "Home/Utilities",
    icon: "🏠",
    color: "#22c55e",
    hint: "Power, water, internet",
    slug: "home-utilities",
  },
  {
    id: crypto.randomUUID(),
    name: "Insurance",
    icon: "🛡️",
    color: "#f97316",
    hint: "Health, auto, home insurance",
    slug: "insurance",
  },

  {
    id: crypto.randomUUID(),
    name: "Entertainment",
    icon: "🎬",
    color: "#6366f1",
    hint: "Movies, concerts",
    slug: "entertainment",
  },
  {
    id: crypto.randomUUID(),
    name: "Shopping",
    icon: "🛍️",
    color: "#06b6d4",
    hint: "Target, Best Buy, Amazon",
    slug: "shopping",
  },
  {
    id: crypto.randomUUID(),
    name: "Amazon",
    icon: "📦",
    color: "#ff9900",
    hint: "Amazon.com orders",
    slug: "amazon",
  },
  {
    id: crypto.randomUUID(),
    name: "Income/Payroll",
    icon: "💼",
    color: "#14b8a6",
    hint: "Direct deposit",
    slug: "income-payroll",
  },
  {
    id: crypto.randomUUID(),
    name: "Transfer: Savings",
    icon: "🔁",
    color: "#a855f7",
    hint: "Move to savings",
    slug: "transfer-savings",
  },
  {
    id: crypto.randomUUID(),
    name: "Transfer: Investing",
    icon: "📈",
    color: "#8b5cf6",
    hint: "Brokerage / 401k",
    slug: "transfer-investing",
  },
  {
    id: crypto.randomUUID(),
    name: "Rent/Mortgage",
    icon: "🏡",
    color: "#84cc16",
    hint: "Housing payments",
    slug: "rent-mortgage",
  },
  {
    id: crypto.randomUUID(),
    name: "Debt",
    icon: "💳",
    color: "#f43f5e",
    hint: "Credit card / loans",
    slug: "debt",
  },
  {
    id: crypto.randomUUID(),
    name: "Impulse/Misc",
    icon: "🎲",
    color: "#fb923c",
    hint: "Gifts, vending machines",
    slug: "impulse-misc",
  },
  {
    id: crypto.randomUUID(),
    name: "Doctors",
    icon: "🩺",
    color: "#38bdf8",
    hint: "Co-pays, clinics",
    slug: "doctors",
  },
  {
    id: crypto.randomUUID(),
    name: "Memberships",
    icon: "🪪",
    color: "#22d3ee",
    hint: "YMCA, Costco, Sam’s",
    slug: "memberships",
  },
  {
    id: crypto.randomUUID(),
    name: "Subscriptions",
    icon: "📺",
    color: "#e879f9",
    hint: "Netflix, Paramount+",
    slug: "subscriptions",
  },
  {
    id: crypto.randomUUID(),
    name: "Cash Back",
    icon: "💵",
    color: "#84cc16",
    hint: "Rewards",
    slug: "cash-back",
  },
  {
    id: crypto.randomUUID(),
    name: "Uncategorized",
    icon: "❓",
    color: "#475569",
    hint: "Unmapped or one-off",
    slug: "uncategorized",
  },
];
