import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReconcilerProvider } from "./providers/ReconcilerProvider";
import { CategoriesProvider } from "./providers/CategoriesProvider";
import Navbar from "@/components/Navbar";
import { AliasesProvider } from "./providers/AliasesProvider";
import AuthProvider from "./providers/AuthProvider";
import { BrandMapProvider } from "./providers/BrandMapProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen overflow-x-hidden antialiased`}
      >
        <AuthProvider>
          <CategoriesProvider>
            <AliasesProvider>
              <ReconcilerProvider>
                <Navbar />
                <BrandMapProvider>
                  <main className="pt-4">{children}</main>
                </BrandMapProvider>
              </ReconcilerProvider>
            </AliasesProvider>
          </CategoriesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
